# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Package

on:
  workflow_dispatch:
  # release:
  #   types: [published]

jobs:
  publish-nuget:
    name: Build, Pack, and Publish NuGet Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

      - name: Restore dependencies
        run: dotnet restore ./csharp

      - name: Build
        run: dotnet build ./csharp --configuration Release --no-restore

      - name: Pack
        run: dotnet pack ./csharp --configuration Release --no-build -o ./dist

      - name: Publish to NuGet
        run: dotnet nuget push "./dist/*.nupkg"
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
